version: '3.8'
networks:
  nginx-proxy:
    external:
      name: reverse-proxy
  back:
    driver: bridge
services:
  app:
    build: .
    container_name: blizheapi
    restart: always
    env_file:
      - .env
    networks:
      - nginx-proxy
      - back
    depends_on:
      - db
    environment:
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_PORT: ${POSTGRES_PORT}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "3000:3000"

  db:
    image: postgres:14
    networks:
      - back
    container_name: blizhe-postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ahan2004
      POSTGRES_DB: main
    volumes:
      - ./data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  nginx:
    image: nginx:latest
    container_name: blizhe-nginx-proxy
    networks:
      - nginx-proxy
    volumes:
      - ./../nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - /etc/letsencrypt/live/blizhe.kz/fullchain.pem:/etc/nginx/ssl/fullchain.pem:ro
      - /etc/letsencrypt/live/blizhe.kz/privkey.pem:/etc/nginx/ssl/privkey.pem:ro
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - app
